// Constants
export const ADD_SUBJECT_MODAL = 'ADD_SUBJECT_MODAL';
export const EDIT_SUBJECT_MODAL = 'EDIT_SUBJECT_MODAL';
export const CWORK = 'CWORK';
export const RESEARCH = 'RESEARCH';
export const ADMINWORK = 'ADMINWORK';
export const EXTANDCOMMSERVICE = 'EXTANDCOMMSERVICE';
export const COURSE = 'COURSE';
export const CONSULTATIONHOUR = 'CONSULTATIONHOUR';

// Action Types
export const TOGGLE_MODAL = 'FSR/TOGGLE_MODAL';
export const NEXT_STEP = 'FSR/NEXT_STEP';
export const PREVIOUS_STEP = 'FSR/PREVIOUS_STEP';
export const GET_FSR = 'FSR/GET_FSR';
export const GET_SUBJECTS = 'FSR/GET_SUBJECTS';
export const ADD_SUBJECT = 'FSR/ADD_SUBJECT';
export const DELETE_SUBJECT = 'FSR/DELETE_SUBJECT';
export const EDIT_SUBJECT = 'FSR/EDIT_SUBJECT';
export const ADD_TIMESLOT = 'FSR/ADD_TIMESLOT';
export const GET_TIMESLOTS = 'FSR/GET_TIMESLOTS';
export const GET_ANNOUNCEMENTS = 'FSR/GET_ANNOUNCEMENTS';
export const GET_NOTIFICATIONS = 'FSR/GET_NOTIFICATIONS';

export const CHANGE_SELECTED_SUBJECT = 'FSR/CHANGE_SELECTED_SUBJECT';
