USE easyfsr;

-- USER
INSERT INTO user (employeeID, password, firstName, middleName, lastName, committee, officeNumber, contractType, emailAddress, acctType) VALUES ('1000335121', '$2a$10$JQL/6dENt1TQofx49huAmu1e/K/m8UPn4SGXixRU5NYDK/QzpudbW', 'Admin', 'Admin', 'Admin', 'Extension', '313', 'FULL-TIME', 'admin@up.edu.ph', 'ADMIN');
INSERT INTO user (employeeID, password, firstName, middleName, lastName, committee, officeNumber, contractType, emailAddress, acctType) VALUES ('1000335120', '$2a$10$JQL/6dENt1TQofx49huAmu1e/K/m8UPn4SGXixRU5NYDK/QzpudbW', 'Lorri', 'Keigher', 'Gherardelli', 'Extension', '313', 'PART-TIME', 'lgherardelli0@techcrunch.com', 'ADMIN');
INSERT INTO user (employeeID, password, firstName, middleName, lastName, committee, officeNumber, contractType, emailAddress) VALUES ('1000466663', '$2a$10$JQL/6dENt1TQofx49huAmu1e/K/m8UPn4SGXixRU5NYDK/QzpudbW', 'Delmer', 'Engeham', 'Bisterfeld', 'Sports', '312', 'FULL-TIME', 'dbisterfeld1@jugem.jp');
INSERT INTO user (employeeID, password, firstName, middleName, lastName, committee, officeNumber, contractType, emailAddress) VALUES ('1000349383', '$2a$10$JQL/6dENt1TQofx49huAmu1e/K/m8UPn4SGXixRU5NYDK/QzpudbW', 'Kathryne', 'Mitchener', 'Bodicam', 'Curriculum & Instruction', '314', 'FULL-TIME', 'kbodicam2@w3.org');
INSERT INTO user (employeeID, password, firstName, middleName, lastName, committee, officeNumber, contractType, emailAddress) VALUES ('1000917030', '$2a$10$JQL/6dENt1TQofx49huAmu1e/K/m8UPn4SGXixRU5NYDK/QzpudbW', 'Carole', 'De Ruggero', 'Dimic', 'Research', '316', 'FULL-TIME', 'cdimic3@oracle.com');
INSERT INTO user (employeeID, password, firstName, middleName, lastName, committee, officeNumber, contractType, emailAddress) VALUES ('1000214330', '$2a$10$JQL/6dENt1TQofx49huAmu1e/K/m8UPn4SGXixRU5NYDK/QzpudbW', 'Charin', 'Baggs', 'Duerden', 'Curriculum & Instruction', '314', 'PART-TIME', 'cduerden4@ebay.co.uk');
INSERT INTO user (employeeID, password, firstName, middleName, lastName, committee, officeNumber, contractType, emailAddress) VALUES ('1000606753', '$2a$10$JQL/6dENt1TQofx49huAmu1e/K/m8UPn4SGXixRU5NYDK/QzpudbW', 'Maude', 'Crass', 'Southwick', 'Sports', '315', 'FULL-TIME', 'msouthwick5@springer.com');
INSERT INTO user (employeeID, password, firstName, middleName, lastName, committee, officeNumber, contractType, emailAddress) VALUES ('1000067174', '$2a$10$JQL/6dENt1TQofx49huAmu1e/K/m8UPn4SGXixRU5NYDK/QzpudbW', 'Thurston', 'Daouse', 'Hastwell', 'Extension', '318', 'FULL-TIME', 'thastwell6@berkeley.edu');
INSERT INTO user (employeeID, password, firstName, middleName, lastName, committee, officeNumber, contractType, emailAddress) VALUES ('1000043866', '$2a$10$JQL/6dENt1TQofx49huAmu1e/K/m8UPn4SGXixRU5NYDK/QzpudbW', 'Aveline', 'Levi', 'Sotham', 'Sports', '313', 'FULL-TIME', 'asotham7@live.com');
INSERT INTO user (employeeID, password, firstName, middleName, lastName, committee, officeNumber, contractType, emailAddress) VALUES ('1000322226', '$2a$10$JQL/6dENt1TQofx49huAmu1e/K/m8UPn4SGXixRU5NYDK/QzpudbW', 'Alessandra', 'Ratnege', 'Newband', 'Curriculum & Instruction', '313', 'FULL-TIME', 'anewband8@zimbio.com');
INSERT INTO user (employeeID, password, firstName, middleName, lastName, committee, officeNumber, contractType, emailAddress) VALUES ('1000944069', '$2a$10$JQL/6dENt1TQofx49huAmu1e/K/m8UPn4SGXixRU5NYDK/QzpudbW', 'Johan', 'Apedaile', 'Kleinmintz', 'Research', '314', 'PART-TIME', 'jkleinmintz9@slideshare.net');
INSERT INTO user (employeeID, password, firstName, middleName, lastName, committee, officeNumber, contractType, emailAddress) VALUES ('1000278856', '$2a$10$JQL/6dENt1TQofx49huAmu1e/K/m8UPn4SGXixRU5NYDK/QzpudbW', 'Nickey', 'MacAdam', 'Gherardelli', 'Alumni Relations', '315', 'PART-TIME', 'ngherardellia@nifty.com');
INSERT INTO user (employeeID, password, firstName, middleName, lastName, committee, officeNumber, contractType, emailAddress) VALUES ('1000359994', '$2a$10$JQL/6dENt1TQofx49huAmu1e/K/m8UPn4SGXixRU5NYDK/QzpudbW', 'Neron', 'Spaldin', 'Goodreid', 'Research', '318', 'PART-TIME', 'ngoodreidb@tuttocitta.it');
INSERT INTO user (employeeID, password, firstName, middleName, lastName, committee, officeNumber, contractType, emailAddress) VALUES ('1000385706', '$2a$10$JQL/6dENt1TQofx49huAmu1e/K/m8UPn4SGXixRU5NYDK/QzpudbW', 'Ethel', 'Brydell', 'Aspital', 'Registration', '312', 'PART-TIME', 'easpitalc@state.tx.us');
INSERT INTO user (employeeID, password, firstName, middleName, lastName, committee, officeNumber, contractType, emailAddress) VALUES ('1000737258', '$2a$10$JQL/6dENt1TQofx49huAmu1e/K/m8UPn4SGXixRU5NYDK/QzpudbW', 'Jeniffer', 'Abrashkin', 'Foulkes', 'Extension', '315', 'PART-TIME', 'jfoulkesd@newyorker.com');
INSERT INTO user (employeeID, password, firstName, middleName, lastName, committee, officeNumber, contractType, emailAddress) VALUES ('1000835940', '$2a$10$JQL/6dENt1TQofx49huAmu1e/K/m8UPn4SGXixRU5NYDK/QzpudbW', 'Aubree', 'Jurgen', 'Banville', 'Registration', '318', 'PART-TIME', 'abanvillee@amazon.co.jp');
INSERT INTO user (employeeID, password, firstName, middleName, lastName, committee, officeNumber, contractType, emailAddress) VALUES ('1000375233', '$2a$10$JQL/6dENt1TQofx49huAmu1e/K/m8UPn4SGXixRU5NYDK/QzpudbW', 'Lilly', 'Boome', 'Caddies', 'Curriculum & Instruction', '316', 'FULL-TIME', 'lcaddiesf@hatena.ne.jp');
INSERT INTO user (employeeID, password, firstName, middleName, lastName, committee, officeNumber, contractType, emailAddress) VALUES ('1000773864', '$2a$10$JQL/6dENt1TQofx49huAmu1e/K/m8UPn4SGXixRU5NYDK/QzpudbW', 'Carlynn', 'Gurney', 'McTrustram', 'Sports', '312', 'FULL-TIME', 'cmctrustramg@mysql.com');
INSERT INTO user (employeeID, password, firstName, middleName, lastName, committee, officeNumber, contractType, emailAddress) VALUES ('1000730899', '$2a$10$JQL/6dENt1TQofx49huAmu1e/K/m8UPn4SGXixRU5NYDK/QzpudbW', 'Jamal', 'Albion', 'Jiras', 'Registration', '316', 'FULL-TIME', 'jjirash@japanpost.jp');
INSERT INTO user (employeeID, password, firstName, middleName, lastName, committee, officeNumber, contractType, emailAddress) VALUES ('1000089260', '$2a$10$JQL/6dENt1TQofx49huAmu1e/K/m8UPn4SGXixRU5NYDK/QzpudbW', 'Sunny', 'Martland', 'Ulyat', 'Extension', '312', 'PART-TIME', 'sulyati@twitter.com');
INSERT INTO user (employeeID, password, firstName, middleName, lastName, committee, officeNumber, contractType, emailAddress) VALUES ('1000477064', '$2a$10$JQL/6dENt1TQofx49huAmu1e/K/m8UPn4SGXixRU5NYDK/QzpudbW', 'Garrett', 'Keitch', 'Ulster', 'Curriculum & Instruction', '312', 'FULL-TIME', 'gulsterj@aboutads.info');
INSERT INTO user (employeeID, password, firstName, middleName, lastName, committee, officeNumber, contractType, emailAddress) VALUES ('1000380417', '$2a$10$JQL/6dENt1TQofx49huAmu1e/K/m8UPn4SGXixRU5NYDK/QzpudbW', 'Hertha', 'Dodgshon', 'Purchase', 'Extension', '318', 'FULL-TIME', 'hpurchasek@usgs.gov');
INSERT INTO user (employeeID, password, firstName, middleName, lastName, committee, officeNumber, contractType, emailAddress) VALUES ('1000741254', '$2a$10$JQL/6dENt1TQofx49huAmu1e/K/m8UPn4SGXixRU5NYDK/QzpudbW', 'Roma', 'Parkin', 'Burdass', 'Sports', '314', 'FULL-TIME', 'rburdassl@cnbc.com');
INSERT INTO user (employeeID, password, firstName, middleName, lastName, committee, officeNumber, contractType, emailAddress) VALUES ('1000795879', '$2a$10$JQL/6dENt1TQofx49huAmu1e/K/m8UPn4SGXixRU5NYDK/QzpudbW', 'Renard', 'Gladdolph', 'Bryenton', 'Extension', '318', 'PART-TIME', 'rbryentonm@jimdo.com');
INSERT INTO user (employeeID, password, firstName, middleName, lastName, committee, officeNumber, contractType, emailAddress) VALUES ('1000260529', '$2a$10$JQL/6dENt1TQofx49huAmu1e/K/m8UPn4SGXixRU5NYDK/QzpudbW', 'Jeane', 'Mowsdell', 'Busk', 'Extension', '313', 'PART-TIME', 'jbuskn@exblog.jp');
INSERT INTO user (employeeID, password, firstName, middleName, lastName, committee, officeNumber, contractType, emailAddress) VALUES ('1000319408', '$2a$10$JQL/6dENt1TQofx49huAmu1e/K/m8UPn4SGXixRU5NYDK/QzpudbW', 'Rickie', 'Ferrai', 'Mullany', 'Registration', '316', 'FULL-TIME', 'rmullanyo@theglobeandmail.com');
INSERT INTO user (employeeID, password, firstName, middleName, lastName, committee, officeNumber, contractType, emailAddress) VALUES ('1000167276', '$2a$10$JQL/6dENt1TQofx49huAmu1e/K/m8UPn4SGXixRU5NYDK/QzpudbW', 'Austin', 'Cino', 'Johannesson', 'Alumni Relations', '313', 'FULL-TIME', 'ajohannessonp@addthis.com');
INSERT INTO user (employeeID, password, firstName, middleName, lastName, committee, officeNumber, contractType, emailAddress) VALUES ('1000342420', '$2a$10$JQL/6dENt1TQofx49huAmu1e/K/m8UPn4SGXixRU5NYDK/QzpudbW', 'Rebecca', 'Battison', 'Benson', 'Sports', '318', 'FULL-TIME', 'rbensonq@boston.com');
INSERT INTO user (employeeID, password, firstName, middleName, lastName, committee, officeNumber, contractType, emailAddress) VALUES ('1000277695', '$2a$10$JQL/6dENt1TQofx49huAmu1e/K/m8UPn4SGXixRU5NYDK/QzpudbW', 'Fergus', 'Kenforth', 'Juckes', 'Alumni Relations', '310', 'PART-TIME', 'fjuckesr@ed.gov');
INSERT INTO user (employeeID, password, firstName, middleName, lastName, committee, officeNumber, contractType, emailAddress) VALUES ('1000597752', '$2a$10$JQL/6dENt1TQofx49huAmu1e/K/m8UPn4SGXixRU5NYDK/QzpudbW', 'Aurora', 'Popov', 'Shinton', 'Curriculum & Instruction', '313', 'PART-TIME', 'ashintons@github.io');
INSERT INTO user (employeeID, password, firstName, middleName, lastName, committee, officeNumber, contractType, emailAddress) VALUES ('1000499810', '$2a$10$JQL/6dENt1TQofx49huAmu1e/K/m8UPn4SGXixRU5NYDK/QzpudbW', 'Bogey', 'Cardero', 'Newlyn', 'Alumni Relations', '312', 'FULL-TIME', 'bnewlynt@google.de');

-- FSR
INSERT INTO fsr (userID, acadYear, semester) VALUES (1, '2017-2018', 'Second');
INSERT INTO fsr (userID, acadYear, semester) VALUES (1, '2017-2018', 'First');
INSERT INTO fsr (userID, acadYear, semester) VALUES (1, '2016-2017', 'Second');
INSERT INTO fsr (userID, acadYear, semester) VALUES (2, '2017-2018', 'Second');
INSERT INTO fsr (userID, acadYear, semester) VALUES (2, '2017-2018', 'First');
INSERT INTO fsr (userID, acadYear, semester) VALUES (2, '2016-2017', 'Second');
INSERT INTO fsr (userID, acadYear, semester) VALUES (3, '2017-2018', 'Second');
INSERT INTO fsr (userID, acadYear, semester) VALUES (3, '2017-2018', 'First');
INSERT INTO fsr (userID, acadYear, semester) VALUES (3, '2016-2017', 'Second');
INSERT INTO fsr (userID, acadYear, semester) VALUES (4, '2017-2018', 'Second');
INSERT INTO fsr (userID, acadYear, semester) VALUES (4, '2017-2018', 'First');
INSERT INTO fsr (userID, acadYear, semester) VALUES (4, '2016-2017', 'Second');
INSERT INTO fsr (userID, acadYear, semester) VALUES (5, '2017-2018', 'Second');
INSERT INTO fsr (userID, acadYear, semester) VALUES (5, '2017-2018', 'First');
INSERT INTO fsr (userID, acadYear, semester) VALUES (5, '2016-2017', 'Second');
INSERT INTO fsr (userID, acadYear, semester) VALUES (6, '2017-2018', 'Second');
INSERT INTO fsr (userID, acadYear, semester) VALUES (6, '2017-2018', 'First');
INSERT INTO fsr (userID, acadYear, semester) VALUES (6, '2016-2017', 'Second');
INSERT INTO fsr (userID, acadYear, semester) VALUES (7, '2017-2018', 'Second');
INSERT INTO fsr (userID, acadYear, semester) VALUES (7, '2017-2018', 'First');
INSERT INTO fsr (userID, acadYear, semester) VALUES (7, '2016-2017', 'Second');
INSERT INTO fsr (userID, acadYear, semester) VALUES (8, '2017-2018', 'Second');
INSERT INTO fsr (userID, acadYear, semester) VALUES (8, '2017-2018', 'First');
INSERT INTO fsr (userID, acadYear, semester) VALUES (8, '2016-2017', 'Second');
INSERT INTO fsr (userID, acadYear, semester) VALUES (9, '2017-2018', 'Second');
INSERT INTO fsr (userID, acadYear, semester) VALUES (9, '2017-2018', 'First');
INSERT INTO fsr (userID, acadYear, semester) VALUES (9, '2016-2017', 'Second');
INSERT INTO fsr (userID, acadYear, semester) VALUES (10, '2017-2018', 'Second');
INSERT INTO fsr (userID, acadYear, semester) VALUES (10, '2017-2018', 'First');
INSERT INTO fsr (userID, acadYear, semester) VALUES (10, '2016-2017', 'Second');
INSERT INTO fsr (userID, acadYear, semester) VALUES (11, '2017-2018', 'Second');
INSERT INTO fsr (userID, acadYear, semester) VALUES (11, '2017-2018', 'First');
INSERT INTO fsr (userID, acadYear, semester) VALUES (11, '2016-2017', 'Second');
INSERT INTO fsr (userID, acadYear, semester) VALUES (12, '2017-2018', 'Second');
INSERT INTO fsr (userID, acadYear, semester) VALUES (12, '2017-2018', 'First');
INSERT INTO fsr (userID, acadYear, semester) VALUES (12, '2016-2017', 'Second');
INSERT INTO fsr (userID, acadYear, semester) VALUES (13, '2017-2018', 'Second');
INSERT INTO fsr (userID, acadYear, semester) VALUES (13, '2017-2018', 'First');
INSERT INTO fsr (userID, acadYear, semester) VALUES (13, '2016-2017', 'Second');
INSERT INTO fsr (userID, acadYear, semester) VALUES (14, '2017-2018', 'Second');
INSERT INTO fsr (userID, acadYear, semester) VALUES (14, '2017-2018', 'First');
INSERT INTO fsr (userID, acadYear, semester) VALUES (14, '2016-2017', 'Second');
INSERT INTO fsr (userID, acadYear, semester) VALUES (15, '2017-2018', 'Second');
INSERT INTO fsr (userID, acadYear, semester) VALUES (15, '2017-2018', 'First');
INSERT INTO fsr (userID, acadYear, semester) VALUES (15, '2016-2017', 'Second');
INSERT INTO fsr (userID, acadYear, semester) VALUES (16, '2017-2018', 'Second');
INSERT INTO fsr (userID, acadYear, semester) VALUES (16, '2017-2018', 'First');
INSERT INTO fsr (userID, acadYear, semester) VALUES (16, '2016-2017', 'Second');
INSERT INTO fsr (userID, acadYear, semester) VALUES (17, '2017-2018', 'Second');
INSERT INTO fsr (userID, acadYear, semester) VALUES (17, '2017-2018', 'First');
INSERT INTO fsr (userID, acadYear, semester) VALUES (17, '2016-2017', 'Second');
INSERT INTO fsr (userID, acadYear, semester) VALUES (18, '2017-2018', 'Second');
INSERT INTO fsr (userID, acadYear, semester) VALUES (18, '2017-2018', 'First');
INSERT INTO fsr (userID, acadYear, semester) VALUES (18, '2016-2017', 'Second');
INSERT INTO fsr (userID, acadYear, semester) VALUES (19, '2017-2018', 'Second');
INSERT INTO fsr (userID, acadYear, semester) VALUES (19, '2017-2018', 'First');
INSERT INTO fsr (userID, acadYear, semester) VALUES (19, '2016-2017', 'Second');
INSERT INTO fsr (userID, acadYear, semester) VALUES (20, '2017-2018', 'Second');
INSERT INTO fsr (userID, acadYear, semester) VALUES (20, '2017-2018', 'First');
INSERT INTO fsr (userID, acadYear, semester) VALUES (20, '2016-2017', 'Second');
INSERT INTO fsr (userID, acadYear, semester) VALUES (21, '2017-2018', 'Second');
INSERT INTO fsr (userID, acadYear, semester) VALUES (21, '2017-2018', 'First');
INSERT INTO fsr (userID, acadYear, semester) VALUES (21, '2016-2017', 'Second');
INSERT INTO fsr (userID, acadYear, semester) VALUES (22, '2017-2018', 'Second');
INSERT INTO fsr (userID, acadYear, semester) VALUES (22, '2017-2018', 'First');
INSERT INTO fsr (userID, acadYear, semester) VALUES (22, '2016-2017', 'Second');
INSERT INTO fsr (userID, acadYear, semester) VALUES (23, '2017-2018', 'Second');
INSERT INTO fsr (userID, acadYear, semester) VALUES (23, '2017-2018', 'First');
INSERT INTO fsr (userID, acadYear, semester) VALUES (23, '2016-2017', 'Second');
INSERT INTO fsr (userID, acadYear, semester) VALUES (24, '2017-2018', 'Second');
INSERT INTO fsr (userID, acadYear, semester) VALUES (24, '2017-2018', 'First');
INSERT INTO fsr (userID, acadYear, semester) VALUES (24, '2016-2017', 'Second');
INSERT INTO fsr (userID, acadYear, semester) VALUES (25, '2017-2018', 'Second');
INSERT INTO fsr (userID, acadYear, semester) VALUES (25, '2017-2018', 'First');
INSERT INTO fsr (userID, acadYear, semester) VALUES (25, '2016-2017', 'Second');
INSERT INTO fsr (userID, acadYear, semester) VALUES (26, '2017-2018', 'Second');
INSERT INTO fsr (userID, acadYear, semester) VALUES (26, '2017-2018', 'First');
INSERT INTO fsr (userID, acadYear, semester) VALUES (26, '2016-2017', 'Second');
INSERT INTO fsr (userID, acadYear, semester) VALUES (27, '2017-2018', 'Second');
INSERT INTO fsr (userID, acadYear, semester) VALUES (27, '2017-2018', 'First');
INSERT INTO fsr (userID, acadYear, semester) VALUES (27, '2016-2017', 'Second');
INSERT INTO fsr (userID, acadYear, semester) VALUES (28, '2017-2018', 'Second');
INSERT INTO fsr (userID, acadYear, semester) VALUES (28, '2017-2018', 'First');
INSERT INTO fsr (userID, acadYear, semester) VALUES (28, '2016-2017', 'Second');
INSERT INTO fsr (userID, acadYear, semester) VALUES (29, '2017-2018', 'Second');
INSERT INTO fsr (userID, acadYear, semester) VALUES (29, '2017-2018', 'First');
INSERT INTO fsr (userID, acadYear, semester) VALUES (29, '2016-2017', 'Second');
INSERT INTO fsr (userID, acadYear, semester) VALUES (30, '2017-2018', 'Second');
INSERT INTO fsr (userID, acadYear, semester) VALUES (30, '2017-2018', 'First');
INSERT INTO fsr (userID, acadYear, semester) VALUES (30, '2016-2017', 'Second');